// Seleções do Mundial — GERADO por gerar_bracket.js (football-data.org).
// `code` = bandeira flagcdn.com. Status/form viram reais quando o gerador
// passar a ler resultados; por ora ficam neutros.
window.TEAMS = [
  { name: "África do Sul", code: "za", status: "Fase de grupos", form: [] },
  { name: "Alemanha", code: "de", status: "Fase de grupos", form: [] },
  { name: "Arábia Saudita", code: "sa", status: "Fase de grupos", form: [] },
  { name: "Argélia", code: "dz", status: "Fase de grupos", form: [] },
  { name: "Argentina", code: "ar", status: "Fase de grupos", form: [] },
  { name: "Austrália", code: "au", status: "Fase de grupos", form: [] },
  { name: "Áustria", code: "at", status: "Fase de grupos", form: [] },
  { name: "Bélgica", code: "be", status: "Fase de grupos", form: [] },
  { name: "Bósnia e Herzegovina", code: "ba", status: "Fase de grupos", form: [] },
  { name: "Brasil", code: "br", status: "Classificado", form: [] },
  { name: "Cabo Verde", code: "cv", status: "Fase de grupos", form: [] },
  { name: "Canadá", code: "ca", status: "Fase de grupos", form: [] },
  { name: "Catar", code: "qa", status: "Fase de grupos", form: [] },
  { name: "Colômbia", code: "co", status: "Fase de grupos", form: [] },
  { name: "Coreia do Sul", code: "kr", status: "Fase de grupos", form: [] },
  { name: "Costa do Marfim", code: "ci", status: "Fase de grupos", form: [] },
  { name: "Croácia", code: "hr", status: "Fase de grupos", form: [] },
  { name: "Curaçau", code: "cw", status: "Fase de grupos", form: [] },
  { name: "Egito", code: "eg", status: "Fase de grupos", form: [] },
  { name: "Equador", code: "ec", status: "Fase de grupos", form: [] },
  { name: "Escócia", code: "gb-sct", status: "Fase de grupos", form: [] },
  { name: "Espanha", code: "es", status: "Fase de grupos", form: [] },
  { name: "Estados Unidos", code: "us", status: "Fase de grupos", form: [] },
  { name: "França", code: "fr", status: "Fase de grupos", form: [] },
  { name: "Gana", code: "gh", status: "Fase de grupos", form: [] },
  { name: "Haiti", code: "ht", status: "Fase de grupos", form: [] },
  { name: "Holanda", code: "nl", status: "Fase de grupos", form: [] },
  { name: "Inglaterra", code: "gb-eng", status: "Fase de grupos", form: [] },
  { name: "Irã", code: "ir", status: "Fase de grupos", form: [] },
  { name: "Iraque", code: "iq", status: "Fase de grupos", form: [] },
  { name: "Japão", code: "jp", status: "Fase de grupos", form: [] },
  { name: "Jordânia", code: "jo", status: "Fase de grupos", form: [] },
  { name: "Marrocos", code: "ma", status: "Fase de grupos", form: [] },
  { name: "México", code: "mx", status: "Fase de grupos", form: [] },
  { name: "Noruega", code: "no", status: "Fase de grupos", form: [] },
  { name: "Nova Zelândia", code: "nz", status: "Fase de grupos", form: [] },
  { name: "Panamá", code: "pa", status: "Fase de grupos", form: [] },
  { name: "Paraguai", code: "py", status: "Fase de grupos", form: [] },
  { name: "Portugal", code: "pt", status: "Fase de grupos", form: [] },
  { name: "RD Congo", code: "cd", status: "Fase de grupos", form: [] },
  { name: "República Tcheca", code: "cz", status: "Fase de grupos", form: [] },
  { name: "Senegal", code: "sn", status: "Fase de grupos", form: [] },
  { name: "Suécia", code: "se", status: "Fase de grupos", form: [] },
  { name: "Suíça", code: "ch", status: "Fase de grupos", form: [] },
  { name: "Tunísia", code: "tn", status: "Fase de grupos", form: [] },
  { name: "Turquia", code: "tr", status: "Fase de grupos", form: [] },
  { name: "Uruguai", code: "uy", status: "Fase de grupos", form: [] },
  { name: "Uzbequistão", code: "uz", status: "Fase de grupos", form: [] }
];

window.DEFAULT_TEAM = "br";
